ESTADOS_CHOICES = (
    (u'AGUASCALIENTES', u'Aguascalientes'),
    (u'BAJA CALIFORNIA', u'Baja California'),
    (u'BAJA CALIFORNIA SUR', u'Baja California Sur'),
    (u'CAMPECHE', u'Campeche'),
    (u'COAHUILA', u'Coahuila'),
    (u'COLIMA', u'Colima'),
    (u'CHIAPAS', u'Chiapas'),
    (u'CHIHUAHUA', u'Chihuahua'),
    (u'DISTRITO FEDERAL', u'Distrito Federal'),
    (u'DURANGO', u'Durango'),
    (u'GUANAJUATO', u'Guanajuato'),
    (u'GUERRERO', u'Guerrero'),
    (u'HIDALGO', u'Hidalgo'),
    (u'JALISCO', u'Jalisco'),
    (u'MEXICO', u'M\u00e9xico'),
    (u'MICHOACAN', u'Michoac\u00e1n'),
    (u'MORELOS', u'Morelos'),
    (u'NAYARIT', u'Nayarit'),
    (u'NUEVO LEON', u'Nuevo Le\u00f3n'),
    (u'OAXACA', u'Oaxaca'),
    (u'PUEBLA', u'Puebla'),
    (u'QUERETARO', u'Quer\u00e9taro'),
    (u'QUINTANA ROO', u'Quintana Roo'),
    (u'SAN LUIS POTOSI', u'San Luis Potos\u00ed'),
    (u'SINALOA', u'Sinaloa'),
    (u'SONORA', u'Sonora'),
    (u'TABASCO', u'Tabasco'),
    (u'TAMAULIPAS', u'Tamaulipas'),
    (u'TLAXCALA', u'Tlaxcala'),
    (u'VERACRUZ', u'Veracr\u00faz'),
    (u'YUCATAN', u'Yucat\u00e1n'),
    (u'ZACATECAS', u'Zacatecas'),
)
